Installed linters and set my portfolio project
sidiksam/My-Portfolio pull request #1
Opened 2022-06-30 22:37 UTC by sidiksam

my portfolio project:
1. set up linters 
2. create an HTML file
3. create a CSS file 
4. build a navigation menu 
5. section 
6. social media  icons

2022-06-30 23:56 UTC, omarsalem7 requested changes
Hi @sidiksam 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
The content is aligned with flexbox ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] It will be better if not give width for every element in page, I suggest to you leave it take a default width because this will help you when try to build desktop version, cheers. 🍻

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 23:56 UTC, omarsalem7 commented on css/style.css
> +  width: 380px;
- [ ] Kindly remove this width to improve your design and make it responsive to all screens not specific width. One of the best practice don't give width for container let him take a default space.

2022-06-30 23:56 UTC, omarsalem7 commented on css/style.css
> +  width: 380px;
- [ ] Also remove width from here as stated before.

2022-06-30 23:56 UTC, omarsalem7 commented on index.html
> +      <p class="laura">Laura John</p>
- [ ] The container of the section is a `section` tag
- [ ] The main title is a `h1` tag not `p`

2022-07-01 01:32 UTC, danielufeli approved these changes
Hi @sidiksam ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 11:12 UTC, merged