Created a modal popup using java script for both mobile and desktop
sidiksam/My-Portfolio pull request #13
Opened 2022-07-22 01:43 UTC by sidiksam

##Modal Popup
### Create a variable and array in the javascript file
### Add some CSS to I
###Add functionality with javascript

2022-07-22 02:17 UTC, Reem-lab requested changes
Hi Team, 👋🏻👋🏻 

Good job so far!🔥🔥✅✅
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linters error ✅✅
- Good working on the functionality✅✅
- Good saving the info in array of objects ✅✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 02:17 UTC, Reem-lab commented on index.html
> +            <div class="mobile-modal" id="modalMobile"></div>
- [ ] According to the requiremnts The projects - all the project - section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for projects list should be removed so kindly remove it and add it dynamically by the js file.🔥💪🏻💪🏻

2022-07-22 02:17 UTC, Reem-lab commented on css/style.css
> +  }
- [ ] As I can see here you need to blur the background behind the pop up because I can't see any thing from the pop card.

- [ ] Kindly make the width and the height the same as the Figma template because it is important to stick with the requirements 🔥💪🏻 

- [ ] I can't see the buttons for live version and source code, and the technologies as well in the card Kindly add them


- Your design
![image](https://user-images.githubusercontent.com/58553711/180347338-1e6227c8-a528-487a-ad2e-0add81c26aa2.png)


- Figma design
![image](https://user-images.githubusercontent.com/58553711/180347444-6813663a-18ae-498e-9d0b-7eaae2ba5c1d.png)

2022-07-22 02:17 UTC, Reem-lab commented on css/style.css
> +  }
- [ ] Breat work but I think here also need blur so Please adjust the blur on the background behind the pop up in the mobile version so I can see the card clearly, because it is not clear here


- Your design
![image](https://user-images.githubusercontent.com/58553711/180347701-6c06b2f1-d8cb-401d-a726-5afed4e0dab6.png)


- Figma design 
![image](https://user-images.githubusercontent.com/58553711/180347853-d23d0996-b0f5-424f-86bb-00f00f21a86c.png)

2022-07-23 04:05 UTC, cwaku requested changes
Hi @sidiksam 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
 - [x] Good job overall following the template design 💯 
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 

## Required Changes ♻️
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them, in order to get your project approved ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 04:05 UTC, cwaku commented on css/style.css
> +  }
- [ ] Just a little bit more to finish the requested change from the previous reviewer. On the desktop version, the "See live" and "See source" buttons are not showing. Kindly resolve that.

Your Design | Figma Design
--|--
![image](https://user-images.githubusercontent.com/29071984/180589699-9ca839ab-8069-40c7-b91e-b30505689644.png) | ![image](https://user-images.githubusercontent.com/29071984/180589669-b37d51e7-a7ef-439e-ad07-3c93cbf2c0d6.png)

2022-07-23 04:15 UTC, sidiksam commented on css/style.css
> +  }
I don't know why the buttons are   not showing on your side but they are showing on my side

2022-07-23 04:17 UTC, sidiksam commented on index.html
> +            <div class="mobile-modal" id="modalMobile"></div>
honestly speaking we don't know how to solve the  problem, we have searched me and my coding partner but we don't know how to solve the broblem

2022-07-23 04:43 UTC, cwaku commented on index.html
> +            <div class="mobile-modal" id="modalMobile"></div>
@sidiksam Kindly have a look at this [example](https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95) to get the idea of how to do this in your project

2022-07-23 04:46 UTC, cwaku commented on css/style.css
> +  }
@sidiksam I suggest you try the app in different viewports to confirm that it behaves as expected in standard screen sizes

2022-07-23 11:07 UTC, Ismailco requested changes
### Hi @sidiksam, @AbigiyaTY, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 11:07 UTC, Ismailco commented on script.js
> +function createCards() {
- [ ]  Good job fixing some of the issues pointed out by the previous reviewer however, the popup card is not rendering correctly, kindly fix this so your design looks like the Figma one

|Your Design|Figma Design|
|-|-|
|![Screenshot_20220723_120259](https://user-images.githubusercontent.com/25227022/180602428-1b0447b2-add4-4769-a5dc-4a4087d03327.png)|![image](https://user-images.githubusercontent.com/29071984/180589669-b37d51e7-a7ef-439e-ad07-3c93cbf2c0d6.png)|

2022-07-23 11:32 UTC, sidiksam commented on script.js
> +function createCards() {
Csn you please guide me how to fix this problem we have tried but the reviewer keep saying the same thing. Please show me how to fix this css problem

2022-07-23 21:47 UTC, mirouhml approved these changes
# APPROVED 🟢

Hi @sidiksam, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e471p9juygtcaesd615kgxa3b2n2dt6xyrzcycnk4b3&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] Please fix your modal in mobile screens, the lower half of the modal should be aligned to the middle, right now it's looking like this:

<img src="https://user-images.githubusercontent.com/20567503/180623750-a735de11-cd0e-4a97-afe2-7dbf7b57306d.png" width=200 />


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 21:53 UTC, merged