Popup maodal
sidiksam/My-Portfolio pull request #16
Opened 2022-07-28 04:51 UTC by sidiksam

- Popup Modal 
- created cards dynamically using javascript
- set the popup modal responsive
- make changes to the HTML file on the eclipse class

2022-07-28 04:57 UTC, Ismailco reviewed
Hi @sidiksam, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some linter errors, kindly make sure all the checks pass

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-28 06:01 UTC, Ginohmk requested changes
Hi @sidiksam , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- No linter errors :+1: 
- Good commit messages :100: 
- Good PR summary :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Your Code reviewer:
- `@kanu mike chibundu`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 00:13 UTC, topeogunleye requested changes
Hi @sidiksam, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
>- [ ] From now on, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Wrong
![image](https://user-images.githubusercontent.com/52934128/181862579-4483ff9d-2059-4b61-b4a3-abd7cd17b684.png)
> ### Good Commit Messages:
>- [x]  Add fix for dark mode toggle state
>- [x] Update README file.
>- [x] Add styles to h1.
>
>- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 00:13 UTC, topeogunleye commented on script.js
> +  <div class="mobileText"><p class="mobileModalText">${mobileModal.descriptionMobile}</p></div>
- [ ] As suggested by the previous reviewer, please work on your pop up modal follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins).
- [ ] As seen in the images below, there is enough space between the programming language and buttons from the Figma Design but there isn't in your design


| Your Design  | Template Design |
| ------------- | ------------- |
| <img width="160" alt="portfolio-1" src="https://user-images.githubusercontent.com/52934128/181862141-94686cf8-d1e8-499d-bdc6-609a58e26411.PNG">  | <img width="144" alt="portfolio-2" src="https://user-images.githubusercontent.com/52934128/181862179-f764dd20-53d6-4165-bd5d-6484e16db8c7.PNG">  |

2022-07-30 00:13 UTC, topeogunleye commented on script.js
> +  <div class="desktopText"><p class="desktopModalText">${desktopModalContent.descriptionDesktop}</p></div>
- [ ] As suggested by the previous reviewer, please work on your pop up modal follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins).
- [ ] As seen in the images below, there is enough space between the programming language and buttons from the Figma Design but there isn't in your design


| Your Design  | Template Design |
| ------------- | ------------- |
| <img width="621" alt="portfolio-4" src="https://user-images.githubusercontent.com/52934128/181862368-fa356c2a-a5fe-4f9c-92f5-c8538d06c01f.PNG"> | <img width="404" alt="portfolio-3" src="https://user-images.githubusercontent.com/52934128/181862317-6cedb60a-ada5-42ab-b984-ce1ab5b59110.PNG"> |

2022-07-30 00:21 UTC, sidiksam commented on script.js
> +  <div class="mobileText"><p class="mobileModalText">${mobileModal.descriptionMobile}</p></div>
So what going on because it display well on my side don't know why its not displaying well on your screen

2022-07-30 00:24 UTC, topeogunleye commented on script.js
> +  <div class="mobileText"><p class="mobileModalText">${mobileModal.descriptionMobile}</p></div>
It should work well on all displays. Can you show me how it looks like on your Laptop

2022-07-30 00:47 UTC, sidiksam commented on script.js
> +  <div class="mobileText"><p class="mobileModalText">${mobileModal.descriptionMobile}</p></div>
#
![Screenshot (17)](https://user-images.githubusercontent.com/46374143/181863688-56e78f81-3da2-43c6-a403-4576997fd346.png)
![Screenshot (18)](https://user-images.githubusercontent.com/46374143/181863690-b91ace95-a3cf-479a-81a8-39b2267deb73.png)

take a look at them here

2022-07-30 09:14 UTC, Ginohmk requested changes
Hi  @sidiksam , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has conflicts, making your linters check not to work, please fix the conflicts and request another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-30 10:43 UTC, closed without merging