Working on the second part of my portfolio
sidiksam/My-Portfolio pull request #2
Opened 2022-07-01 18:03 UTC by sidiksam

My Portfolio second section:
1. border
2. language
3. framework 
4. skills
5. recent work
6. tags 
7. button

2022-07-01 19:47 UTC, vickymarz requested changes
Hi @sidiksam, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
- [x] Kindly ensure that all the title ("Multiple Post Stories") for each project is wrapped in a header tag hx (i.e h2-h6). This is particularly good to make your code semantic 😄 as it describes the heading(title) of the project.
e.g `<h3 class="myRecentWork">Multiple Post Stories</h3>`

- [x] I will strongly recommend you wrap all the list of project technologies ("Html", "Bootstrap" and "Ruby") in a `ul` tag and each of them a `li` tag. Doing this is good for your website accessibility 😄 so that web browsers and screen readers will be able to interpret it as a list.
- [x] The project requirement expects you to work on the **about section** of the portfolio project but I can see that it is missing. Kindly add it 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 19:47 UTC, vickymarz commented on index.html
> +      <p class="myRecentWork">MY RECENT WORK</p>
- [ ] KIndly ensure that your title ("My Recent Works") is wrapped in a header tag `hx` (i.e h2-h6). This is particularly good to make your code semantic 😄.
e.g `<h2 class="myRecentWork">MY RECENT WORK</h2>`

2022-07-01 19:47 UTC, vickymarz commented on index.html
> +          <p>Multiple Post Stories</p>
- [ ] Kindly ensure that your project title ("Multiple Post Stories") is wrapped in a header tag hx (i.e h2-h6). This is particularly good to make your code semantic 😄 as it describes the heading(title) of the project.
e.g `<h3 class="myRecentWork">Multiple Post Stories</h3>`

2022-07-01 19:47 UTC, vickymarz commented on index.html
> +        </div>
- [ ] I will strongly recommend you wrap the list of project technologies ("Html", "Bootstrap" and "Ruby") in a `ul` tag and each of them a `li` tag. Doing this is good for your website accessibility 😄 so that web browsers and screen readers will be able to interpret it as a list.

2022-07-01 19:47 UTC, vickymarz commented on index.html
> +      <p class="myRecentWork">MY RECENT WORK</p>
- [ ] I can see that the contents of the works section are not properly aligned in your design. As I have earlier suggested, you can fix the issue of alignment by using `display: grid` for the layout as specified in the requirement. 😄

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/176959616-d7b1a685-a2c4-426e-a25f-91579d89bb82.png) | ![image](https://user-images.githubusercontent.com/63473584/176959697-7a582743-0207-4d7e-8c74-c15b3954ae67.png)  |

2022-07-02 00:30 UTC, codecaiine requested changes
Hi @sidiksam , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
The Pull Request is following the GitHub Flow :heavy_check_mark: 
The PR title and description are professional and descriptive  :heavy_check_mark: 
Linters are working properly  :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 00:30 UTC, codecaiine commented on index.html
> +      <p class="work">
- [ ] Goog job, you forgot to use a section tag for this part. I'm bouncing on what the previous reviewer mentioned [here](https://github.com/sidiksam/My-Portfolio/pull/2/files#r912189926) the container of the work `section` should be a `section`  tag because the `section`  tag and for this part of your project you are grouping several elements. The best practice suggests using the 'section' tag which is suitable for the accessibility of your project by web browsers.

2022-07-02 07:55 UTC, wuletawwonte approved these changes
## STATUS: APPROVED ♻️♻️
Hi @sidiksam  👋🏿👋🏿👋🏿, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/bedaa87cf63a4eb642948910de3563599306694dfb7118796862f47e55d90651/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f546466794b724e3748475449592f67697068792e676966)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Your PR has a proper title and description ✔️
- Nice commit history ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-02 07:55 UTC, wuletawwonte commented on css/style.css
> +}
- [ ] [OPTIONAL] Please remove the border of the `See Project` button. It has got no border in the Figma design. You can say `border: none`.

2022-07-02 08:10 UTC, merged